# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ansible1" do |ansible1|
    ansible1.vm.box = "geerlingguy/centos7"
    ansible1.vm.network "private_network", type: "static", ip: "192.168.99.10"
    ansible1.vm.hostname = "ansible1"
    ansible1.vm.provider "virtualbox" do |v|
      v.name = "ansible1"
      v.memory = 4096
      v.cpus = 2
    end
    ansible1.vm.provision :shell do |shell|
      shell.path = "install_ansible.sh"
      shell.args = ["master", "192.168.99.10"]
    end
  end
  clients=2
  ram_client=2048
  cpu_client=2
  (1..clients).each do |i|
    config.vm.define "client#{i}" do |client|
      client.vm.box = "geerlingguy/centos7"
      client.vm.network "private_network", type: "static", ip: "192.168.99.1#{i}"
      client.vm.hostname = "client#{i}"
      client.vm.provider "virtualbox" do |v|
        v.name = "client#{i}"
        v.memory = ram_client
        v.cpus = cpu_client
      end
      client.vm.provision :shell do |shell|
        shell.path = "install_ansible.sh"
        shell.args = ["node", "192.168.99.10"]
      end
    end
  end
end

