- hosts: prod
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - ../files/secrets/credentials.yaml
  become: yes
  tasks:
    - name: create build directory
      file:
        path: /root/demo-dockerfile
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ../../Dockerfile
        dest: /root/demo-dockerfile/Dockerfile
        owner: root
        group: root
        mode: '0644'
    - name: copy src
      copy:
        src: ../../src
        dest: /root/demo-dockerfile/src
        owner: root
        group: root
        mode: '0644'
    - name: build container image
      docker_image:
        name: static
        build:
          path: /root/demo-dockerfile
        source: build
        state: present
        push: yes
        repository: "localhost:5000:latest"
