- hosts: prod
  gather_facts: no
  vars_files:
    - '{{ credentials_path }}'
  become: yes
  tasks:
    - name: delete build directory if exists
      file:
        path: /root/demo-dockerfile
        state: absent
    - name: create build directory
      file:
        path: /root/demo-dockerfile
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ../../docker/Dockerfile
        dest: /root/demo-dockerfile/Dockerfile
        owner: root
        group: root
        mode: '0644'
    - name: copy src
      copy:
        src: ../../src
        dest: /root/demo-dockerfile
        owner: root
        group: root
        mode: '0644'
    - name: build container image
      docker_image:
        name: "{{ image_name }}"
        build:
          path: /root/demo-dockerfile
        force_source: yes
        source: build
        state: present
        push: yes
        tag: latest
