---
- name: Monitoring du site en prod
  hosts: prod
  become: yes
  tags:
    - monitoring
  vars_files:
    - "{{ credentials_path }}"
  tasks:
    - name: Curl website
      command: curl --silent -I "{{ inventory_hostname }}"
