---
- name: Run Docker registry
  hosts: prod
  vars_files:
    - '{{ credentials_path }}'
  tasks:
    - name: Run registry
      become: yes
      docker_container:
        name: "registry-container"
        image: "registry"
        state: started
        restart: "yes"
        ports: "5000:5000"
