---
- name: Run production container
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  tags:
    - prod
  vars_files:
    - ../files/secrets/credentials.yaml
  tasks:
    - name: Run in prod
      docker_container:
        name: website-production
        image: localhost:5000/static
        restart: yes
        exposed_ports:
          - 80
