---
- name: Run production container
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  tags:
    - prod
  vars_files:
    - '{{ credentials_path }}'
  tasks:
    - name: Run in prod
      docker_container:
        name: website-production
        image: '{{ image_name }}'
        restart: yes
        exposed_ports:
          - 80
