---
- name: Run production container
  hosts: prod
  become: yes
  tags:
    - prod
  vars_files:
    - '{{ credentials_path }}'
  tasks:
    - name: Run in prod
      docker_container:
        name: website-production
        image: '{{ image_name }}'
        restart: yes
        published_ports:
          - "80:80"
